### ISSUE TITLE
"yoo_WAY_OF"

### ISSUE THREAD

**Issue by kishiyamat** [inagasaki/CHILDES_JMOR#1]
* `lex` ディレクトリ下の `closed.cut` に
`kata	{[scat vsfx] [sfxcat n] [allo OR vV vCi vPIw vAIt vTKi vTSi vAIs]} "kata_WAY_OF"` というのがあるので同様に`yoo	{[scat vsfx] [sfxcat n] [allo OR vV vCi vPIw vAIt vTKi vTSi vAIs]} "yoo_WAY_OF"`という項目がほしいです。
    * 心の配りよう、気の持ちよう、など
* ただ、 allo OR vV...の部分が複雑なので手がつけられません。

**Comment by inagasaki** [comment]
ありがとうございます。

yoo {[scat vsfx] [sfxcat n] [allo OR vV vCi vPIw vAIt vTKi vTSi vAIs]} "yoo_WAY_OF" を 0ksnk_misc.cut に加えていただけますか？
vV vCi ... というのは、動詞語幹末の音によってどう処理するかというようなことなので、（おそらく）kata と同じでいいのだろうと思います。

**Comment by kishiyamat** [comment]
承知いたしました、ありがとうございます。
